/**
 * ====================================================================
 * [팀원 3 담당 구역] Export & Asset Packaging Module
 * ====================================================================
 * 역할: 생성된 앨범 아트워크, A&R 기획서, 홍보 카피를 번들로 묶어
 *       다운로드하거나 클립보드에 원클릭으로 복사하는 클라이언트 기능을 담당합니다.
 */

class ExportManager {
  constructor() {
    this.currentData = null;
  }

  setData(data) {
    this.currentData = data;
  }

  /**
   * 홍보 텍스트를 클립보드에 복사하고 버튼 텍스트를 일시적으로 변경
   */
  async copyToClipboard(text, buttonElement) {
    try {
      await navigator.clipboard.writeText(text);
      const originalText = buttonElement.innerText;
      buttonElement.innerText = "✅ 클립보드 복사 완료!";
      buttonElement.style.borderColor = "var(--accent-cyan)";
      buttonElement.style.color = "var(--accent-cyan)";

      setTimeout(() => {
        buttonElement.innerText = originalText;
        buttonElement.style.borderColor = "";
        buttonElement.style.color = "";
      }, 2000);
    } catch (err) {
      console.error("[ExportManager] 복사 실패:", err);
      alert("클립보드 복사에 실패했습니다. 수동으로 텍스트를 복사해 주세요.");
    }
  }

  /**
   * 브라우저 기반 릴리즈 브리프 텍스트 파일 다운로드
   * (추후 백엔드 ZIP 압축 다운로드 API `/api/export-zip` 또는 JSZip 라이브러리와 연동)
   */
  downloadReleaseBundle() {
    if (!this.currentData) {
      alert("생성된 프로젝트 데이터가 없습니다.");
      return;
    }

    const { concept_report, marketing_copy, audio_features } = this.currentData;

    const bundleText = `=====================================================
[Indie Album Studio] 앨범 브랜딩 & 발매 릴리즈 키트
=====================================================
프로젝트명: ${concept_report.project_title}
로그라인: ${concept_report.logline}

[1. 오디오 분석 지표]
• BPM: ${audio_features.bpm}
• 음색 밝기: ${audio_features.spectral_brightness}
• 다이내믹 에너지: ${audio_features.rms_energy}
• 추천 장르: ${audio_features.detected_genres.join(', ')}

[2. A&R 콘셉트 서사]
${concept_report.core_narrative}

[3. 추천 컬러 팔레트]
${concept_report.color_palette.map(c => `- ${c.name} (${c.hex}) : ${c.role}`).join('\n')}

[4. 비주얼 사조 키워드]
${concept_report.art_movement_keywords.join(', ')}

=====================================================
[5. 플랫폼별 홍보 카피라이팅]
=====================================================

--- [멜론 / 지니 / 벅스 공식 트랙 소개글] ---
${marketing_copy.melon_intro}

--- [인스타그램 릴리즈 홍보 캡션] ---
${marketing_copy.insta_caption}

=====================================================
Generated by Indie Album Studio (AI Native Audio Studio)
`;

    const blob = new Blob([bundleText], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${concept_report.project_title.replace(/\s+/g, '_')}_Release_Kit.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    alert("📦 릴리즈 텍스트 키트 다운로드가 시작되었습니다!\n(백엔드 Render 서버 연동 시 고화질 아트워크 3종이 포함된 .zip 파일로 다운로드됩니다.)");
  }
}

// Global ExportManager instance
window.exportManager = new ExportManager();
